[package]
name = "wordgrid_solver"
version = "0.1.0"
edition = "2021"

[lib]
name = "wordgrid_solver"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.2", features = ["extension-module"] } # For Python bindings
rand = "0.8" # For random number generation
